# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
before_install:
- gem install cocoapods -v 0.33.1
- cd Example && pod install && cd ..
- brew update
- brew unlink xctool && brew install xctool --HEAD
script:
- xctool test -workspace Example/YapDatabaseCJKFullTextSearch.xcworkspace -scheme YapDatabaseCJKFullTextSearch -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
